# Starship Configuration

format = """
[](fg:#7aa2f7)$os[](fg:#7aa2f7 bg:#1a1b26)$directory$git_branch$git_status$git_metrics[](fg:#1a1b26)$fill[](fg:#1a1b26)$python[](fg:#1a1b26)\n$character"""

right_format = """
$cmd_duration
$nodejs
$java
$kotlin
$time
"""

[os]
format = "[$symbol]($style)"
style = 'fg:#1a1b26 bg:#7aa2f7'
disabled = false

[os.symbols]
Macos = " "

[directory]
truncation_length = 6
truncation_symbol = '…/'
truncate_to_repo = false
home_symbol = " ~"
style = 'fg:#7aa2f7 bg:#1a1b26'
read_only = "  "
read_only_style = 'fg:#f7768e bg:#1a1b26'
format = '[$path]($style)[$read_only]($read_only_style)'

[git_branch]
symbol = " "
truncation_length = 20
truncation_symbol = ''
style = 'fg:#7aa2f7 bg:#1a1b26'
format = '[  $symbol$branch(:$remote_branch)]($style)'

[git_status]
style = 'fg:#e0af68 bg:#1a1b26'
format = '([\[$all_status$ahead_behind\]]($style))'

[git_metrics]
added_style = 'fg:#9ece6a bg:#1a1b26'
deleted_style = 'fg:#9ece6a bg:#1a1b26'
format = '[+$added/-$deleted]($deleted_style)'
disabled = false

[fill]
symbol = '─'
style = 'blue'

[python]
symbol = " "
format = '[ ${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)'
pyenv_version_name = false
style = 'fg:#1a1b26 bg:#9ece6a'

[character]
success_symbol = '[❯](bold #9ece6a)'
error_symbol = '[❯](bold red)'

[cmd_duration]
min_time = 1
style = 'fg:#e0af68'
format = "[  $duration]($style)"

[nodejs]
symbol = " "
format = '[  $symbol$version](green)'
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]

[java]
symbol = " "
format = '[  $symbol$version](red)'
detect_files = ["pom.xml", "build.gradle", "build.gradle.kts", ".java-version"]

[kotlin]
symbol = " "
format = '[  $symbol$version](purple)'
detect_files = ["build.gradle.kts"]
detect_extensions = ["kt"]

[time]
disabled = false
style = 'fg:#73daca'
format = "[  $time]($style)"
time_format = '%T'
utc_time_offset = '+9'

[aws]
disabled = true
[gcloud]
disabled = true
[docker_context]
disabled = true
[package]
disabled = true
[conda]
disabled = true
